@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: e8b3cfc3e633b9261bb5a4137a25eb0207b599bcea2b76da64c679870d0f8232267c75bcf286de5c1341baffb3e5a691ab21b135b9c7450de199cda84a632e13

{
    "name": "ShopDev",
    "email": "shopdev@gmail.com",
    "password": "abc123"
}

### login
