@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 94e0af8461900fdca4ef8c4b6ecabce3b9b8fa44d4a658d23269ba18216d2bd2f5b4b5a2d98e9e700438a2d6e83f6b1eab0d0aaf8947a173a550f4397903ec01

{
    "name": "Shop Test",
    "email": "shoptest2@gmail.com",
    "password": "1234"
}

### login
